version: "2.0"
services:
  postgres:
    build:
      context: postgres
    image: postgres_image
    container_name: postgres-container
    ports:
      - "5432:5432"
    env_file:
      - postgres/.env


  backend:
    build:
      context: ./
    container_name: cloudpi-api
    #    env_file:
    #      - Password-Keeper-API/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres